# Generated by Django 5.0.2 on 2024-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrarCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='CadastrarEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('caixas', models.IntegerField(verbose_name='Caixas')),
                ('volumeextra', models.CharField(max_length=150, verbose_name='Volume Extra')),
                ('nomeembalador', models.CharField(max_length=100, verbose_name='Nome do Embalador')),
                ('datacompra', models.DateField(verbose_name='Data da Compra')),
                ('dataentrega', models.DateField(verbose_name='Data da Entrega')),
            ],
        ),
    ]
