# Generated by Django 5.0.2 on 2024-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cadastrarentrega_volumeextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrarentrega',
            name='volumeextra',
            field=models.CharField(blank=True, default='Sem volume extra', max_length=150, null=True, verbose_name='Volume Extra'),
        ),
    ]
